name: PushBack
version: 1.1
main: com.reflexian.pushback.PushBack
description: A simple pushback plugin
website: Reflexian.com
author: RaymondDev
commands:
  pushback:
    usage: /<command>
    description: The main command to trigger PushBack